CREATE TABLE Accounts (
    AccNo INT PRIMARY KEY,
    HolderName VARCHAR(50),
    Balance INT
);

INSERT INTO Accounts VALUES
(1, 'Aarati', 1000),
(2, 'Anita', 1000);

SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
START TRANSACTION;
UPDATE Accounts SET Balance = Balance - 200 WHERE AccNo = 1;
-- (No commit yet)

SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
START TRANSACTION;
SELECT Balance FROM Accounts WHERE AccNo = 1;